tap "ebc-2in2crc/zlibcmd"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jeffreywildman/virt-manager"
cask "osxfuse"
brew "ant"
brew "openssl@1.1"
brew "binutils"
brew "cmake"
brew "colordiff"
brew "doxygen"
brew "ext4fuse"
brew "xz"
brew "gmp"
brew "mpfr"
brew "libmpc"
brew "gnupg", link: false
brew "gnupg@1.4", link: false
brew "graphviz"
brew "hardlink-osx"
brew "libsodium"
brew "mercurial"
brew "ngircd", restart_service: true, link: false
brew "pipenv"
brew "postgresql"
brew "protobuf"
brew "ruby-build"
brew "rbenv"
brew "rbenv-gemset"
brew "ruby"
brew "thefuck"
brew "tree"
brew "unar", link: false
brew "zsh"
brew "ebc-2in2crc/zlibcmd/zlibcmd"
brew "python"
brew "pixman"
brew "cairo"
brew "jpeg"
brew "pango"
brew "anttweakbar"
brew "pkg-config"
brew "coreutils"
brew "curl"
brew "exiftool"
brew "ffmpeg", args: ["with-fdk-aac"]
brew "freeimage"
brew "giflib"
brew "git"
brew "glew"
brew "glfw"
brew "gnu-sed"
brew "go"
brew "gradle"
brew "grep"
brew "gst-plugins-base", link: false
brew "gst-libav"
brew "gst-plugins-bad"
brew "gst-plugins-good"
brew "gst-plugins-ugly"
brew "imagemagick"
brew "kotlin"
brew "lua"
brew "luarocks"
brew "mas"
brew "mono"
brew "mysql"
brew "ncftp"
brew "nkf"
brew "node", link: false
brew "node@10"
brew "node@8", link: true
brew "php"
brew "pulseaudio"
brew "py3cairo"
brew "pyenv"
brew "pygobject3"
brew "qemu"
brew "sl"
brew "sshfs"
brew "telnet"
brew "tmux"
brew "vte3"
brew "wget"
brew "youtube-dl"
brew "jeffreywildman/virt-manager/virt-manager"
brew "jeffreywildman/virt-manager/virt-viewer"
cask "alacritty"
cask "chromedriver"
cask "docker"
cask "dotnet-sdk"
cask "gitup"
cask "istat-menus"
cask "java"
cask "jd-gui"
cask "adoptopenjdk8"
cask "visual-studio-code"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Apple Configurator 2", id: 1037126344
mas "Display Menu", id: 549083868
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
mas "DfontSplitter", id: 1470820747

